# Generated by Django 5.0.4 on 2024-07-12 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_rename_created_by_room_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="message",
            new_name="content",
        ),
    ]
